/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Defence_System.View.defences;

import Defence_System.Util.Observer;
import Defence_System.View.MainControler;

/**
 *
 * @author dilan
 */
public class Submarine extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Submarine
     */
    private MainControler mainControler;
    private int number;
    
     public Submarine(){
        initComponents();
    }
    
    
    public Submarine(MainControler mainControler,int number) {
        this.mainControler=mainControler;
        this.number=number;
                
        initComponents();
        btnShoot.setEnabled(false);
        btnSonar.setEnabled(false);
        btnTomahawk.setEnabled(false);
        btnTrident.setEnabled(false);
        setTitle("Submarine");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnTomahawk = new javax.swing.JButton();
        btnSonar = new javax.swing.JButton();
        btnTrident = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txt01 = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblSoldierCount = new javax.swing.JLabel();
        lblAmmoCount = new javax.swing.JLabel();
        position = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSlider1Submarine02 = new javax.swing.JSlider();
        jSliderSubmarine01 = new javax.swing.JSlider();
        energy = new javax.swing.JLabel();
        oxigen = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        mainLbl01 = new javax.swing.JLabel();
        mainLbl02 = new javax.swing.JLabel();
        mainLbl03 = new javax.swing.JLabel();
        mainLbl04 = new javax.swing.JLabel();
        mainLbl05 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("Area Not Cleared");
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 120, 20));

        btnShoot.setText("Shoot");
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });
        getContentPane().add(btnShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 137, 34));

        btnTomahawk.setText("Tomahawk Missile");
        getContentPane().add(btnTomahawk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 137, 34));

        btnSonar.setText("Sonar Operation");
        getContentPane().add(btnSonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 137, 34));

        btnTrident.setText("Trident 2 Missile");
        getContentPane().add(btnTrident, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 137, 34));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 473, 115));

        txt01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt01ActionPerformed(evt);
            }
        });
        getContentPane().add(txt01, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 383, -1));

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 72, -1));

        lblSoldierCount.setForeground(new java.awt.Color(255, 255, 255));
        lblSoldierCount.setText("Soldier Count");
        getContentPane().add(lblSoldierCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 77, 29));

        lblAmmoCount.setBackground(new java.awt.Color(204, 204, 204));
        lblAmmoCount.setForeground(new java.awt.Color(255, 255, 255));
        lblAmmoCount.setText("Ammo Count");
        getContentPane().add(lblAmmoCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 79, 29));

        position.setText("Posotion");
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });
        getContentPane().add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 51, 29));

        jSlider1Submarine02.setBackground(new java.awt.Color(153, 153, 153));
        jSlider1Submarine02.setMajorTickSpacing(20);
        jSlider1Submarine02.setMinorTickSpacing(10);
        jSlider1Submarine02.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1Submarine02.setPaintLabels(true);
        jSlider1Submarine02.setPaintTicks(true);
        jSlider1Submarine02.setSnapToTicks(true);
        getContentPane().add(jSlider1Submarine02, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 78, 51, 308));

        jSliderSubmarine01.setBackground(new java.awt.Color(153, 153, 153));
        jSliderSubmarine01.setMajorTickSpacing(20);
        jSliderSubmarine01.setMinorTickSpacing(10);
        jSliderSubmarine01.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderSubmarine01.setPaintLabels(true);
        jSliderSubmarine01.setPaintTicks(true);
        jSliderSubmarine01.setSnapToTicks(true);
        getContentPane().add(jSliderSubmarine01, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 78, -1, 308));

        energy.setText("Energy");
        getContentPane().add(energy, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 44, 45, 28));

        oxigen.setText("Oxigen");
        getContentPane().add(oxigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 45, 59, 26));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 51, 29));

        mainLbl01.setBackground(new java.awt.Color(153, 153, 153));
        mainLbl01.setOpaque(true);
        getContentPane().add(mainLbl01, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 0, 180, 410));

        mainLbl02.setBackground(new java.awt.Color(0, 0, 0));
        mainLbl02.setOpaque(true);
        getContentPane().add(mainLbl02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 70));

        mainLbl03.setBackground(new java.awt.Color(102, 102, 102));
        mainLbl03.setOpaque(true);
        getContentPane().add(mainLbl03, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 220, 160));

        mainLbl04.setBackground(new java.awt.Color(153, 153, 153));
        mainLbl04.setOpaque(true);
        getContentPane().add(mainLbl04, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 160));

        mainLbl05.setBackground(new java.awt.Color(51, 51, 51));
        mainLbl05.setOpaque(true);
        getContentPane().add(mainLbl05, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 610, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionActionPerformed

    private void txt01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt01ActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        mainControler.setSMS(txt01.getText(), number);
    }//GEN-LAST:event_btnSendActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        mainControler.setSoldierCount((int)jSpinner1.getValue(), number);
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        mainControler.setAmmoCount((int)jSpinner3.getValue(), number);
    }//GEN-LAST:event_jSpinner3StateChanged

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShootActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnSonar;
    private javax.swing.JButton btnTomahawk;
    private javax.swing.JButton btnTrident;
    private javax.swing.JLabel energy;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JSlider jSlider1Submarine02;
    public static javax.swing.JSlider jSliderSubmarine01;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JLabel lblAmmoCount;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblSoldierCount;
    private javax.swing.JLabel mainLbl01;
    private javax.swing.JLabel mainLbl02;
    private javax.swing.JLabel mainLbl03;
    private javax.swing.JLabel mainLbl04;
    private javax.swing.JLabel mainLbl05;
    private javax.swing.JLabel oxigen;
    private javax.swing.JCheckBox position;
    private javax.swing.JTextField txt01;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changeArea(String area) {
        lblArea.setText(area);
    }

    @Override
    public void changeSlider(int slider) {
        if(position.isSelected()){
            if(slider>=80){
                btnShoot.setEnabled(true);
                btnSonar.setEnabled(true);
                btnTomahawk.setEnabled(true);
                btnTrident.setEnabled(true);  
            }else if(slider>=60){
                btnShoot.setEnabled(true);
                btnSonar.setEnabled(true);
                btnTomahawk.setEnabled(true);
                btnTrident.setEnabled(false);  
            }else if(slider>=40){
                btnShoot.setEnabled(true);
                btnSonar.setEnabled(true);
                btnTomahawk.setEnabled(false);
                btnTrident.setEnabled(false);
            }else if(slider>=20){
                btnShoot.setEnabled(true);
                btnSonar.setEnabled(false);
                btnTomahawk.setEnabled(false);
                btnTrident.setEnabled(false);
            }else{
                btnShoot.setEnabled(false);
                btnSonar.setEnabled(false);
                btnTomahawk.setEnabled(false);
                btnTrident.setEnabled(false);
            }
        }
    }

    @Override
    public void sendMessage(String sms) {
        txtArea.setText(sms);
    }

   

   
}
