/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Defence_System.View.defences;

import Defence_System.Util.Observer;
import Defence_System.View.MainControler;

import javax.swing.text.Position;

/**
 *
 * @author dilan
 */
public class Tank extends javax.swing.JFrame implements Observer{

    /**
     reates new form Tank
     */
    private MainControler mainControler;
    private int number;
    
     public Tank(){
        initComponents();
    }
    
    public Tank(MainControler mainControler,int number) {
        this.mainControler=mainControler;
        this.number=number;
        
        initComponents();
        btnShoot.setEnabled(false);
        btnMissile.setEnabled(false);
        btnRedar.setEnabled(false);
        btnRotat.setEnabled(false);
        setTitle("Tank");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnRedar = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        btnRotat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txeArea = new javax.swing.JTextArea();
        txt01 = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblSoldier = new javax.swing.JLabel();
        lblAmmo = new javax.swing.JLabel();
        position = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        silderTank = new javax.swing.JSlider();
        lblEnergyTank = new javax.swing.JLabel();
        mainLbl01 = new javax.swing.JLabel();
        mainLbl02 = new javax.swing.JLabel();
        mainLbl03 = new javax.swing.JLabel();
        mainLbl04 = new javax.swing.JLabel();
        mainLbl05 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("Area Not Cleared");
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 112, 22));

        btnShoot.setText("Shoot");
        getContentPane().add(btnShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 168, 31));

        btnRedar.setText("Redar Operation");
        getContentPane().add(btnRedar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 168, 31));

        btnMissile.setText("Missile Operator");
        btnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 168, 31));

        btnRotat.setText("Rotat Shooting");
        getContentPane().add(btnRotat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 168, 31));

        txeArea.setColumns(20);
        txeArea.setRows(5);
        jScrollPane1.setViewportView(txeArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 470, 132));
        getContentPane().add(txt01, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 380, -1));

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 77, -1));

        lblSoldier.setForeground(new java.awt.Color(255, 255, 255));
        lblSoldier.setText("Soldier Count");
        getContentPane().add(lblSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 70, 32));

        lblAmmo.setForeground(new java.awt.Color(255, 255, 255));
        lblAmmo.setText("Ammo Count");
        getContentPane().add(lblAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 70, 35));

        position.setText("Position");
        getContentPane().add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 46, -1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 46, -1));

        silderTank.setBackground(new java.awt.Color(153, 153, 153));
        silderTank.setMajorTickSpacing(20);
        silderTank.setMinorTickSpacing(10);
        silderTank.setOrientation(javax.swing.JSlider.VERTICAL);
        silderTank.setPaintLabels(true);
        silderTank.setPaintTicks(true);
        silderTank.setSnapToTicks(true);
        getContentPane().add(silderTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, 297));

        lblEnergyTank.setText("Energy");
        getContentPane().add(lblEnergyTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 40, 20));

        mainLbl01.setBackground(new java.awt.Color(0, 0, 0));
        mainLbl01.setOpaque(true);
        getContentPane().add(mainLbl01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        mainLbl02.setBackground(new java.awt.Color(153, 153, 153));
        mainLbl02.setOpaque(true);
        getContentPane().add(mainLbl02, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 130, 380));

        mainLbl03.setBackground(new java.awt.Color(102, 102, 102));
        mainLbl03.setOpaque(true);
        getContentPane().add(mainLbl03, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 180, 110));

        mainLbl04.setBackground(new java.awt.Color(153, 153, 153));
        mainLbl04.setOpaque(true);
        getContentPane().add(mainLbl04, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 110));

        mainLbl05.setBackground(new java.awt.Color(51, 51, 51));
        mainLbl05.setOpaque(true);
        getContentPane().add(mainLbl05, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 620, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMissileActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        mainControler.setSMS(txt01.getText(), number);
    }//GEN-LAST:event_btnSendActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        mainControler.setSoldierCount((int)jSpinner1.getValue(), number);
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        mainControler.setAmmoCount((int)jSpinner2.getValue(), number);
    }//GEN-LAST:event_jSpinner2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnRedar;
    private javax.swing.JButton btnRotat;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblAmmo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblEnergyTank;
    private javax.swing.JLabel lblSoldier;
    private javax.swing.JLabel mainLbl01;
    private javax.swing.JLabel mainLbl02;
    private javax.swing.JLabel mainLbl03;
    private javax.swing.JLabel mainLbl04;
    private javax.swing.JLabel mainLbl05;
    private javax.swing.JCheckBox position;
    public static javax.swing.JSlider silderTank;
    private javax.swing.JTextArea txeArea;
    private javax.swing.JTextField txt01;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changeArea(String area) {
        lblArea.setText(area);
    }

    @Override
    public void changeSlider(int slider) {
     if(position.isSelected()){
            if(slider>=80){
                btnShoot.setEnabled(true);
                btnMissile.setEnabled(true);
                btnRedar.setEnabled(true);
                btnRotat.setEnabled(true);  
            }else if(slider>=60){
                btnShoot.setEnabled(true);
                btnMissile.setEnabled(true);
                btnRedar.setEnabled(true);
                btnRotat.setEnabled(false);  
            }else if(slider>=40){
                btnShoot.setEnabled(true);
                btnMissile.setEnabled(true);
                btnRedar.setEnabled(false);
                btnRotat.setEnabled(false);
            }else if(slider>=20){
                btnShoot.setEnabled(true);
                btnMissile.setEnabled(false);
                btnRedar.setEnabled(false);
                btnRotat.setEnabled(false);
            }else{
                btnShoot.setEnabled(false);
                btnMissile.setEnabled(false);
                btnRedar.setEnabled(false);
                btnRotat.setEnabled(false);
            }
        }
    }

    @Override
    public void sendMessage(String sms) {
        txeArea.setText(sms);
   }

    

   
}
